<?xml version="1.0" ?>
<robot name="obstacle"  xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:arg name="height" default="1"/>
    <xacro:arg name="width" default="1" />


    <link name="obstacle_link">
        <collision>
            <origin xyz="0 0 ${ $(arg height)/2}" rpy="0 0 0"/>
            <geometry>
                <box size="$(arg width) $(arg width) $(arg height)"/>
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 ${ $(arg height)/2}" rpy="0 0 0"/>
            <geometry>
                <box size="$(arg width) $(arg width) $(arg height)"/>
            </geometry>
            <material name="orange"/>
        </visual>

        <inertial>
            <origin xyz="0 0 1" rpy="0 0 0"/>
            <mass value="1"/>
            <inertia
                ixx="1.0" ixy="0.0" ixz="0.0"
                iyy="1.0" iyz="0.0"
                izz="1.0"/>
        </inertial>

    </link>
</robot>